#!/bin/bash

export GIT_AUTHOR_NAME="Zuzana Jeschke"
export GIT_COMMITTER_NAME="Zuzana Jeschke"
export GIT_COMMITTER_EMAIL=zuz@zuzjes.com
export GIT_AUTHOR_EMAIL=zuz@zuzjes.com

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1)\$ '
